services:
  - type: web
    name: thrive-toolkit-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.main:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: OLLAMA_BASE_URL
        value: http://localhost:11434
      - key: MODEL_NAME
        value: llama3-8b-8192